version: "3"

services:
  light-chaser:
    image: "light-chaser:1.3.0"
    container_name: light-chaser-container
    depends_on:
      - light-chaser-server
    volumes:
      - /usr/app/light-chaser/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - light-chaser-network
    ports:
      - "80:80"


  light-chaser-server:
    image: "light-chaser-server:1.3.0"
    container_name: light-chaser-server-container
    volumes:
      - /usr/app/light-chaser-server/config/application.yml:/config/application.yml
      - /usr/app/light-chaser-server/source:/usr/app/resource
      - /usr/app/light-chaser-server/logs:/usr/app/light-chaser-server/logs
    environment:
      - SPRING_CONFIG_LOCATION=/config/application.yml
    networks:
      - light-chaser-network
    ports:
      - "8080:8080"

networks:
  light-chaser-network:
    driver: bridge
