spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:./data/light_chaser_server.db
    username: 
    password: 
    # 使用HikariCP连接池
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000




# mybatis-plus配置
mybatis-plus:
  type-aliases-package: com.dagu.lightchaser.entity
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


light-chaser:
  project-resource-path: ./data/resources # 项目资源路径
  source-image-path: /static/images/ # 源图片路径
  cover-path: /static/covers/ # 封面路径
  migration: # 是否自动跑sql脚本
    enable: true

#logging:
#  config: classpath:log4j2-spring.xml
#  level:
#    cn.jay.repository: trace
